### ISSUE TITLE
[Feature request] - Expiry

### ISSUE THREAD

**Issue by Tanddant** [bellstrand/totp-generator#19]
Let me start by saying perhaps I just don't know enough about TOTP!

But it would be really neat to know when the current code expires, perhaps just a callback method that triggers when the key expires, that way I could make a responsive UI that doesn't need to recalculate the value every second just to verify if it's changed.

**Comment by bellstrand** [comment]
@Tanddant Your token change based on on the `period` you use. You could calculate when the token needs to be refreshed with `period - Date.now() / 1000 % period` (that would give you a value in seconds). Since the token is based on the clock everything is just an estimate, because this relies on that the clock on both the client and server matches.

**Comment by Tanddant** [comment]
Awesome, that makes sense, thanks a ton!
